---
# tasks file for Jenkins

- name: fix a defect to disable setup wizard
  jenkins_script:
    script: |
      import static jenkins.model.Jenkins.instance as jenkins
      import jenkins.install.InstallState
      if (!jenkins.installState.isSetupComplete()) {
        InstallState.INITIAL_SETUP_COMPLETED.initializeState()
      }
    user: "admin"
    password: "admin"

- name: Install tools
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - jq
